import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import QueryProvider from "@/providers/query-provider";
import Header from "./components/header";
import { cn } from "@/lib/utils";
import { Toaster } from "sonner";
import { ClerkProvider } from "@clerk/nextjs";
// import BoughtProducts from "@/components/bought-products";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body
          className={cn(
            "md:pt-3 px-2 py-1  md:pr-5 md:pl-5 shrink-0 md:shrink",
            inter.className
          )}
        >
          <QueryProvider>
            {/* <BoughtProducts /> */}
            <Toaster position="top-center" />

            {children}
          </QueryProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
